spring.application.name=Live-stream


SERVER.PORT = 8080



spring.datasource.url=jdbc:mysql://localhost:3306/livestream
spring.datasource.username=root
spring.datasource.password=Kisha@2006

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect